(let ((config-dir (file-name-directory load-file-name))
      (modules '(
                 "bootstrap/my-bootstrap.el"
                 "bootstrap/my-straight.el"
                 ;; "bootstrap/my-esup.el"
                 "editor/my-settings.el"
                 "editor/my-plugins.el"
                 "editor/my-commands.el"
                 "editor/asmr.el"
                 "looks/my-settings.el"
                 "looks/my-theme.el"
                 "looks/my-auto-margin.el"
                 "looks/my-doom-modeline.el"
                 "keybindings/my-base.el"
                 "keybindings/my-ijkl.el"
                 "keybindings/my-keybindings.el"
                 "keybindings/my-transient.el"
                 ;; "keybindings/my-tabs.el"
                 "org/my-org-mode.el"
                 "org/my-notes.el"
                 "org/my-present.el"
                 "prog/my-settings.el"
                 "prog/my-compilation.el"
                 "prog/my-commands.el"
                 "prog/my-git.el"
                 "prog/my-plugins.el"
                 "prog/my-markdown.el"
                 "prog/my-web.el"
                 "prog/my-c++.el"
                 "prog/my-python.el"
                 "prog/my-yaml.el"
                 "prog/my-docker.el"
                 "prog/my-outline.el"
                 "prog/my-corfu.el"
                 "prog/my-linters.el"
                 "prog/my-eglot.el"
                 "prog/my-lsp-mode.el"
                 )))
  (mapcar (lambda(filename) (load (concat config-dir filename))) modules))

